// @ts-nocheck
import Head from "next/head";
import { useFormState } from "react-dom";
import { signIn } from "@/signin";
import { useEffect } from "react";
import { redirect } from "next/navigation";
import { useRouter } from "next/router";

export default function Home() {
  const [signInState, signInAction] = useFormState(signIn, { error: null });
  const router = useRouter();
  useEffect(() => {
        console.log(signInState);
        if (signInState['user']) {
          let accessToken = signInState['accessToken']
          setTimeout(()=>{
            router.push(`http://localhost:3000/ws-callback?access_token=${accessToken}`)
          }, 2000)
        };
  }, [signInState, router]);

  return (
    <>
      <Head>
        <title>Sign-in to GatewayHR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { signInState['error']? (<p className="error">{signInState['error']?.message}</p>): ''}
      { signInState['user']? (<p className="success">Login success.</p>): ''}
      <main>
        <h1>Sign-in</h1>

        <form action={signInAction}>
          <div className="finput">
            <label className="label" htmlFor="email">Email</label>
            <input
              type="email"
              name="email"
              id="email"
              autoCapitalize="off"
              autoComplete="username"
              autoFocus
              required
            />
          </div>

          <div className="finput">
            <label className="label" htmlFor="password">Password</label>
            <input
              type="password"
              name="password"
              id="password"
              autoCapitalize="off"
              autoComplete="current-password"
              required
            />
          </div>

          <button className="formsubmit" type="submit">Sign-in</button>
        </form>
      </main>
    </>
  );
}
